name: Build, Test, Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    # Job Setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o 'artifacts/statscraper'

    # Login into Azure Client
    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create Resources
    - name: ARM Deploy - Create App Service Resoures
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: .github/workflows/azf-template.json

    # Deploy Code
    - name: Deploy Azure Function
      uses: Azure/functions-action@v1
      with: 
            app-name: ${{ secrets.AZF_NAME }}
            package: 'artifacts/statscraper'

    # Post Deployment
    - name: Post Deploy Configuration
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          id=$(az webapp identity assign -n ${{ secrets.AZF_NAME }} -g ${{ secrets.AZURE_RG }} | jq -r '.principalId')
          az keyvault set-policy -n ${{ secrets.VAULT_NAME }} --secret-permissions get list --object-id $id
